# Generated by Django 6.0.3 on 2026-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Cliente', max_length=200)),
                ('correo', models.CharField(help_text='Correo electrónico', max_length=200)),
                ('teléfono', models.IntegerField(help_text='Número de Teléfono', max_length=200)),
                ('empresa', models.CharField(help_text='Nombre de su empresa', max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
            ],
        ),
    ]
