# Generated by Django 6.0.3 on 2026-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='teléfono',
            field=models.IntegerField(help_text='Número de Teléfono'),
        ),
    ]
